imagePullSecrets: {}

installation:
  enabled: true
  kubernetesProvider: ""

apiServer:
  enabled: true

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

calicoNetwork:
  ipPools:
  - blockSize: 26
    cidr: 10.244.0.0/16
    encapsulation: VXLANCrossSubnet
    natOutgoing: Enabled
    nodeSelector: all()
  nodeAddressAutodetectionV4:
    interface: "eth.*"

# Configuration for the tigera operator
tigeraOperator:
  image: tigera/operator
  version: v1.20.0
  registry: quay.mirrors.ustc.edu.cn
calicoctl:
  image: calico/ctl
  tag: v3.20.0
  registry: quay.mirrors.ustc.edu.cn
