imagePullSecrets: {}

installation:
  enabled: true
  kubernetesProvider: ""
  calicoNetwork:
    nodeAddressAutodetectionV4:
      interface: "enp.*"

apiServer:
  enabled: true

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

calicoNetwork:
  nodeAddressAutodetectionV4:
    interface: "enp.*"
  ipPools:
  - blockSize: 26
    cidr: 10.244.0.0/16
    encapsulation: VXLANCrossSubnet
    natOutgoing: Enabled
    nodeSelector: all()
  # https://www.fireballman.com/resolve-failed-calico-node-bird-is-not-ready/

# Configuration for the tigera operator
tigeraOperator:
  image: tigera/operator
  version: v1.20.0
  registry: quay.mirrors.ustc.edu.cn
calicoctl:
  image: calico/ctl
  tag: v3.20.0
  registry: quay.mirrors.ustc.edu.cn
