apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
  - grafana.woaisok8s.com
  http:
  - route:
    - destination:
        host: monitor-grafana
        port:
          number: 80
  gateways:
    - https-gateway

