apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
spec:
  selector:
    matchLabels:
      app: mysql-client
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-client
    spec:
      containers:
      - name: mysql
        image: bitnami/mysql:8.0.26-debian-10-r10
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 128Mi
            cpu: 100mi
