apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
  namespace: tools
spec:
  selector:
    matchLabels:
      app: mysql-client
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-client
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: mysql
        image: bitnami/mysql:8.0.26-debian-10-r10
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
